//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenTrabajo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenTrabajo()
        {
            this.RepuestoOrden = new HashSet<RepuestoOrden>();
        }
    
        public int idOrdenTrabajo { get; set; }
        public System.DateTime fechaIngreso { get; set; }
        public string detalle { get; set; }
        public int idVehiculo { get; set; }
        public int idEmpleado { get; set; }
        public bool cerrada { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RepuestoOrden> RepuestoOrden { get; set; }
    }
}
