//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepuestoOrden
    {
        public int idRepuestoOrden { get; set; }
        public Nullable<int> cantidadHs { get; set; }
        public int cantidadRepuesto { get; set; }
        public int idOrdenTrabajo { get; set; }
        public int idRepuesto { get; set; }
    
        public virtual OrdenTrabajo OrdenTrabajo { get; set; }
        public virtual Repuesto Repuesto { get; set; }
    }
}
